# Default values for opa-operator.
options:
  imagePullPolicy:
    type: string
    description: |
      Image pull policy. Valid values are Always, IfNotPresent and Never
    default: "Always"
  release:
    default: v3.9.0
    description: Version of OPA controller manager to deploy
    type: string

