# Default values for opa-operator.
options:
  release:
    default: ""
    description: Version of OPA controller manager to deploy
    type: string
  log-level:
    default: INFO
    description: Set gatekeeper log level. For example, DEBUG, INFO, WARNING, ERROR.
    type: string

