apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ExamplePolicy
metadata:
  name: example-policy
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    labels: ["gatekeeper"]
